from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_medical_pdf(report_data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        name='MainTitle', 
        parent=styles['Heading1'], 
        fontSize=24, 
        textColor=colors.HexColor('#0F766E'), 
        spaceAfter=20,
        alignment=1 # Center
    )
    
    heading_style = ParagraphStyle(
        name='SubTitle', 
        parent=styles['Heading2'], 
        fontSize=16, 
        textColor=colors.HexColor('#1E293B'), 
        spaceAfter=10,
        spaceBefore=15
    )
    
    normal_style = styles['Normal']
    normal_style.fontSize = 11
    normal_style.spaceAfter = 8
    
    bold_style = ParagraphStyle(
        name='NormalBold',
        parent=normal_style,
        fontName='Helvetica-Bold'
    )
    
    story = []
    
    # 1. Title
    story.append(Paragraph("AI Medical Report", title_style))
    story.append(Spacer(1, 10))
    
    # 2. Patient Info (If any)
    story.append(Paragraph("Patient Information", heading_style))
    story.append(Paragraph("Generated by: Arogya AI Care", normal_style))
    story.append(Spacer(1, 10))
    
    # Extract data securely
    score = report_data.get('health_score', 'N/A')
    
    # 4. Health Score
    story.append(Paragraph(f"Aggregated Health Score: {score} / 100", bold_style))
    story.append(Spacer(1, 10))
    
    # 5. Final AI Diagnosis (Extracted properly)
    story.append(Paragraph("🧠 Final AI Diagnosis", heading_style))
    diseases = report_data.get('diseases', [])
    if isinstance(diseases, list) and diseases:
        for idx, d in enumerate(diseases):
            prefix = "Primary" if idx == 0 else "Secondary"
            story.append(Paragraph(f"• <b>{prefix} Condition:</b> {d}", normal_style))
    else:
         story.append(Paragraph("No critical diseases flagged in this report.", normal_style))
    story.append(Spacer(1, 10))

    # 3. Extracted Values
    story.append(Paragraph("Extracted Clinical Vitals", heading_style))
    extracted = report_data.get('extractedValues', {})
    
    table_data = [['Parameter', 'Status', 'Interpretation']]
    if isinstance(extracted, dict) and extracted:
        for key, val_obj in extracted.items():
            name = key.replace('_', ' ').title()
            status = val_obj.get('status', 'Unknown')
            interp = val_obj.get('interpretation', '')
            table_data.append([name, status, interp])
    else:
        table_data.append(['No Vitals Extracted', '-', '-'])
        
    t = Table(table_data, colWidths=[120, 100, 280])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F766E')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('VALIGN', (0,0), (-1,-1), 'TOP')
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    # 6. Clinical Insights
    story.append(Paragraph("Clinical Insights", heading_style))
    insights = report_data.get('insights', [])
    if isinstance(insights, list) and insights:
        for ins in insights:
            story.append(Paragraph(f"• {ins}", normal_style))
    else:
        story.append(Paragraph("No specific insights.", normal_style))
        
    # 7. Doctor Explanation
    story.append(Paragraph("Doctor's Explanation", heading_style))
    explanation = report_data.get('explanation', '')
    if explanation:
        story.append(Paragraph(explanation, normal_style))
    else:
        story.append(Paragraph("No explicit explanation generated.", normal_style))
        
    # 8. Recommendations
    story.append(Paragraph("Recommendations", heading_style))
    recs = report_data.get('recommendations', [])
    if isinstance(recs, list) and recs:
        for rec in recs:
            title = rec.get('title', '')
            desc = rec.get('desc', '')
            story.append(Paragraph(f"• <b>{title}:</b> {desc}", normal_style))
    else:
        story.append(Paragraph("No specific recommendations at this time.", normal_style))

    doc.build(story)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
